spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:./data/keycloak;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
        
keycloak:
  server:
    context-path: /auth
    username: admin
    password: admin
    context-redirect: true
    
    #migration:
     # importProvider: singleFile
      #importLocation: keycloak-realm-config.json

logging:
  level:
    root: ERROR
    #org.jgroups: TRACE
    #org.infinispan: INFO
    #org.keycloak: DEBUG
    #org.keycloak.services.managers.DefaultBruteForceProtector: WARN
    #org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner: ERROR
    #org.keycloak.services.managers.UserSessionManager: ERROR
    #org.keycloak.timer.basic: ERROR
    #org.apache.wicket.Application: ERROR
